version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: presenca_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: presenca
      MYSQL_USER: presenca
      MYSQL_PASSWORD: presenca123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d

volumes:
  mysql_data: 