version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: paulaelucas_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: paulaelucas_mysql
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    networks:
      - presenca_network
    command: --default-authentication-plugin=mysql_native_password
    security_opt:
      - no-new-privileges:true

networks:
  presenca_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local 